const moveNames = [
{ name:"Karate Chop"},
{ name:"Pound"},
{ name:"Double Slap"},
{ name:"Comet Punch"},
{ name:"Mega Punch"},
{ name:"Pay Day"},
{ name:"Fire Punch"},
{ name:"Ice Punch"},
{ name:"Thunder Punch"},
{ name:"Scratch"},
{ name:"Vice Grip"},
{ name:"Guillotine"},
{ name:"Razor Wind"},
{ name:"Swords Dance"},
{ name:"Cut"},
{ name:"Gust"},
{ name:"Wing Attack"},
{ name:"Whirlwind"},
{ name:"Fly"},
{ name:"Bind"},
{ name:"Slam"},
{ name:"Vine Whip"},
{ name:"Stomp"},
{ name:"Double Kick"},
{ name:"Mega Kick"},
{ name:"Jump Kick"},
{ name:"Rolling Kick"},
{ name:"Sand Attack"},
{ name:"Headbutt"},
{ name:"Horn Attack"},
{ name:"Fury Attack"},
{ name:"Horn Drill"},
{ name:"Tackle"},
{ name:"Body Slam"},
{ name:"Wrap"},
{ name:"Take Down"},
{ name:"Thrash"},
{ name:"Double-Edge"},
{ name:"Tail Whip"},
{ name:"Poison Sting"},
{ name:"Twineedle"},
{ name:"Pin Missile"},
{ name:"Leer"},
{ name:"Bite"},
{ name:"Growl"},
{ name:"Roar"},
{ name:"Sing"},
{ name:"Supersonic"},
{ name:"Sonic Boom"},
{ name:"Disable"},
{ name:"Acid"},
{ name:"Ember"},
{ name:"Flamethrower"},
{ name:"Mist"},
{ name:"Water Gun"},
{ name:"Hydro Pump"},
{ name:"Surf"},
{ name:"Ice Beam"},
{ name:"Blizzard"},
{ name:"Psybeam"},
{ name:"Bubble Beam"},
{ name:"Aurora Beam"},
{ name:"Hyper Beam"},
{ name:"Peck"},
{ name:"Drill Peck"},
{ name:"Submission"},
{ name:"Low Kick"},
{ name:"Counter"},
{ name:"Seismic Toss"},
{ name:"Strength"},
{ name:"Absorb"},
{ name:"Mega Drain"},
{ name:"Leech Seed"},
{ name:"Growth"},
{ name:"Razor Leaf"},
{ name:"Solar Beam"},
{ name:"Poison Powder"},
{ name:"Stun Spore"},
{ name:"Sleep Powder"},
{ name:"Petal Dance"},
{ name:"String Shot"},
{ name:"Dragon Rage"},
{ name:"Fire Spin"},
{ name:"Thunder Shock"},
{ name:"Thunderbolt"},
{ name:"Thunder Wave"},
{ name:"Thunder"},
{ name:"Rock Throw"},
{ name:"Earthquake"},
{ name:"Fissure"},
{ name:"Dig"},
{ name:"Toxic"},
{ name:"Confusion"},
{ name:"Psychic"},
{ name:"Hypnosis"},
{ name:"Meditate"},
{ name:"Agility"},
{ name:"Quick Attack"},
{ name:"Rage"},
{ name:"Teleport"},
{ name:"Night Shade"},
{ name:"Mimic"},
{ name:"Screech"},
{ name:"Double Team"},
{ name:"Recover"},
{ name:"Harden"},
{ name:"Minimize"},
{ name:"Smokescreen"},
{ name:"Confuse Ray"},
{ name:"Withdraw"},
{ name:"Defense Curl"},
{ name:"Barrier"},
{ name:"Light Screen"},
{ name:"Haze"},
{ name:"Reflect"},
{ name:"Focus Energy"},
{ name:"Bide"},
{ name:"Metronome"},
{ name:"Mirror Move"},
{ name:"Self-Destruct"},
{ name:"Egg Bomb"},
{ name:"Lick"},
{ name:"Smog"},
{ name:"Sludge"},
{ name:"Bone Club"},
{ name:"Fire Blast"},
{ name:"Waterfall"},
{ name:"Clamp"},
{ name:"Swift"},
{ name:"Skull Bash"},
{ name:"Spike Cannon"},
{ name:"Constrict"},
{ name:"Amnesia"},
{ name:"Kinesis"},
{ name:"Soft-Boiled"},
{ name:"High Jump Kick"},
{ name:"Glare"},
{ name:"Dream Eater"},
{ name:"Poison Gas"},
{ name:"Barrage"},
{ name:"Leech Life"},
{ name:"Lovely Kiss"},
{ name:"Sky Attack"},
{ name:"Transform"},
{ name:"Bubble"},
{ name:"Dizzy Punch"},
{ name:"Spore"},
{ name:"Flash"},
{ name:"Psywave"},
{ name:"Splash"},
{ name:"Acid Armor"},
{ name:"Crabhammer"},
{ name:"Explosion"},
{ name:"Fury Swipes"},
{ name:"Bonemerang"},
{ name:"Rest"},
{ name:"Rock Slide"},
{ name:"Hyper Fang"},
{ name:"Sharpen"},
{ name:"Conversion"},
{ name:"Tri Attack"},
{ name:"Super Fang"},
{ name:"Slash"},
{ name:"Substitute"},
{ name:"Struggle"},
{ name:"Sketch"},
{ name:"Triple Kick"},
{ name:"Thief"},
{ name:"Spider Web"},
{ name:"Mind Reader"},
{ name:"Nightmare"},
{ name:"Flame Wheel"},
{ name:"Snore"},
{ name:"Curse"},
{ name:"Flail"},
{ name:"Conversion 2"},
{ name:"Aeroblast"},
{ name:"Cotton Spore"},
{ name:"Reversal"},
{ name:"Spite"},
{ name:"Powder Snow"},
{ name:"Protect"},
{ name:"Mach Punch"},
{ name:"Scary Face"},
{ name:"Feint Attack"},
{ name:"Sweet Kiss"},
{ name:"Belly Drum"},
{ name:"Sludge Bomb"},
{ name:"Mud-Slap"},
{ name:"Octazooka"},
{ name:"Spikes"},
{ name:"Zap Cannon"},
{ name:"Foresight"},
{ name:"Destiny Bond"},
{ name:"Perish Song"},
{ name:"Icy Wind"},
{ name:"Detect"},
{ name:"Bone Rush"},
{ name:"Lock-On"},
{ name:"Outrage"},
{ name:"Sandstorm"},
{ name:"Giga Drain"},
{ name:"Endure"},
{ name:"Charm"},
{ name:"Rollout"},
{ name:"False Swipe"},
{ name:"Swagger"},
{ name:"Milk Drink"},
{ name:"Spark"},
{ name:"Fury Cutter"},
{ name:"Steel Wing"},
{ name:"Mean Look"},
{ name:"Attract"},
{ name:"Sleep Talk"},
{ name:"Heal Bell"},
{ name:"Return"},
{ name:"Present"},
{ name:"Frustration"},
{ name:"Safeguard"},
{ name:"Pain Split"},
{ name:"Sacred Fire"},
{ name:"Magnitude"},
{ name:"Dynamic Punch"},
{ name:"Megahorn"},
{ name:"Dragon Breath"},
{ name:"Baton Pass"},
{ name:"Encore"},
{ name:"Pursuit"},
{ name:"Rapid Spin"},
{ name:"Sweet Scent"},
{ name:"Iron Tail"},
{ name:"Metal Claw"},
{ name:"Vital Throw"},
{ name:"Morning Sun"},
{ name:"Synthesis"},
{ name:"Moonlight"},
{ name:"Hidden Power"},
{ name:"Cross Chop"},
{ name:"Twister"},
{ name:"Rain Dance"},
{ name:"Sunny Day"},
{ name:"Crunch"},
{ name:"Mirror Coat"},
{ name:"Psych Up"},
{ name:"Extreme Speed"},
{ name:"Ancient Power"},
{ name:"Shadow Ball"},
{ name:"Future Sight"},
{ name:"Rock Smash"},
{ name:"Whirlpool"},
{ name:"Beat Up"},
{ name:"Fake Out"},
{ name:"Uproar"},
{ name:"Stockpile"},
{ name:"Spit Up"},
{ name:"Swallow"},
{ name:"Heat Wave"},
{ name:"Hail"},
{ name:"Torment"},
{ name:"Flatter"},
{ name:"Will-O-Wisp"},
{ name:"Memento"},
{ name:"Facade"},
{ name:"Focus Punch"},
{ name:"Smelling Salts"},
{ name:"Follow Me"},
{ name:"Nature Power"},
{ name:"Charge"},
{ name:"Taunt"},
{ name:"Helping Hand"},
{ name:"Trick"},
{ name:"Role Play"},
{ name:"Wish"},
{ name:"Assist"},
{ name:"Ingrain"},
{ name:"Superpower"},
{ name:"Magic Coat"},
{ name:"Recycle"},
{ name:"Revenge"},
{ name:"Brick Break"},
{ name:"Yawn"},
{ name:"Knock Off"},
{ name:"Endeavor"},
{ name:"Eruption"},
{ name:"Skill Swap"},
{ name:"Imprison"},
{ name:"Refresh"},
{ name:"Grudge"},
{ name:"Snatch"},
{ name:"Secret Power"},
{ name:"Dive"},
{ name:"Arm Thrust"},
{ name:"Camouflage"},
{ name:"Tail Glow"},
{ name:"Luster Purge"},
{ name:"Mist Ball"},
{ name:"Feather Dance"},
{ name:"Teeter Dance"},
{ name:"Blaze Kick"},
{ name:"Mud Sport"},
{ name:"Ice Ball"},
{ name:"Needle Arm"},
{ name:"Slack Off"},
{ name:"Hyper Voice"},
{ name:"Poison Fang"},
{ name:"Crush Claw"},
{ name:"Blast Burn"},
{ name:"Hydro Cannon"},
{ name:"Meteor Mash"},
{ name:"Astonish"},
{ name:"Weather Ball"},
{ name:"Aromatherapy"},
{ name:"Fake Tears"},
{ name:"Air Cutter"},
{ name:"Overheat"},
{ name:"Odor Sleuth"},
{ name:"Rock Tomb"},
{ name:"Silver Wind"},
{ name:"Metal Sound"},
{ name:"Grass Whistle"},
{ name:"Tickle"},
{ name:"Cosmic Power"},
{ name:"Water Spout"},
{ name:"Signal Beam"},
{ name:"Shadow Punch"},
{ name:"Extrasensory"},
{ name:"Sky Uppercut"},
{ name:"Sand Tomb"},
{ name:"Sheer Cold"},
{ name:"Muddy Water"},
{ name:"Bullet Seed"},
{ name:"Aerial Ace"},
{ name:"Icicle Spear"},
{ name:"Iron Defense"},
{ name:"Block"},
{ name:"Howl"},
{ name:"Dragon Claw"},
{ name:"Frenzy Plant"},
{ name:"Bulk Up"},
{ name:"Bounce"},
{ name:"Mud Shot"},
{ name:"Poison Tail"},
{ name:"Covet"},
{ name:"Volt Tackle"},
{ name:"Magical Leaf"},
{ name:"Water Sport"},
{ name:"Calm Mind"},
{ name:"Leaf Blade"},
{ name:"Dragon Dance"},
{ name:"Rock Blast"},
{ name:"Shock Wave"},
{ name:"Water Pulse"},
{ name:"Doom Desire"},
{ name:"Psycho Boost"},
{ name:"Roost"},
{ name:"Gravity"},
{ name:"Miracle Eye"},
{ name:"Wake-Up Slap"},
{ name:"Hammer Arm"},
{ name:"Gyro Ball"},
{ name:"Healing Wish"},
{ name:"Brine"},
{ name:"Natural Gift"},
{ name:"Feint"},
{ name:"Pluck"},
{ name:"Tailwind"},
{ name:"Acupressure"},
{ name:"Metal Burst"},
{ name:"U-turn"},
{ name:"Close Combat"},
{ name:"Payback"},
{ name:"Assurance"},
{ name:"Embargo"},
{ name:"Fling"},
{ name:"Psycho Shift"},
{ name:"Trump Card"},
{ name:"Heal Block"},
{ name:"Wring Out"},
{ name:"Power Trick"},
{ name:"Gastro Acid"},
{ name:"Lucky Chant"},
{ name:"Me First"},
{ name:"Copycat"},
{ name:"Power Swap"},
{ name:"Guard Swap"},
{ name:"Punishment"},
{ name:"Last Resort"},
{ name:"Worry Seed"},
{ name:"Sucker Punch"},
{ name:"Toxic Spikes"},
{ name:"Heart Swap"},
{ name:"Aqua Ring"},
{ name:"Magnet Rise"},
{ name:"Flare Blitz"},
{ name:"Force Palm"},
{ name:"Aura Sphere"},
{ name:"Rock Polish"},
{ name:"Poison Jab"},
{ name:"Dark Pulse"},
{ name:"Night Slash"},
{ name:"Aqua Tail"},
{ name:"Seed Bomb"},
{ name:"Air Slash"},
{ name:"X-Scissor"},
{ name:"Bug Buzz"},
{ name:"Dragon Pulse"},
{ name:"Dragon Rush"},
{ name:"Power Gem"},
{ name:"Drain Punch"},
{ name:"Vacuum Wave"},
{ name:"Focus Blast"},
{ name:"Energy Ball"},
{ name:"Brave Bird"},
{ name:"Earth Power"},
{ name:"Switcheroo"},
{ name:"Giga Impact"},
{ name:"Nasty Plot"},
{ name:"Bullet Punch"},
{ name:"Avalanche"},
{ name:"Ice Shard"},
{ name:"Shadow Claw"},
{ name:"Thunder Fang"},
{ name:"Ice Fang"},
{ name:"Fire Fang"},
{ name:"Shadow Sneak"},
{ name:"Mud Bomb"},
{ name:"Psycho Cut"},
{ name:"Zen Headbutt"},
{ name:"Mirror Shot"},
{ name:"Flash Cannon"},
{ name:"Rock Climb"},
{ name:"Defog"},
{ name:"Trick Room"},
{ name:"Draco Meteor"},
{ name:"Discharge"},
{ name:"Lava Plume"},
{ name:"Leaf Storm"},
{ name:"Power Whip"},
{ name:"Rock Wrecker"},
{ name:"Cross Poison"},
{ name:"Gunk Shot"},
{ name:"Iron Head"},
{ name:"Magnet Bomb"},
{ name:"Stone Edge"},
{ name:"Captivate"},
{ name:"Stealth Rock"},
{ name:"Grass Knot"},
{ name:"Chatter"},
{ name:"Judgment"},
{ name:"Bug Bite"},
{ name:"Charge Beam"},
{ name:"Wood Hammer"},
{ name:"Aqua Jet"},
{ name:"Attack Order"},
{ name:"Defend Order"},
{ name:"Heal Order"},
{ name:"Head Smash"},
{ name:"Double Hit"},
{ name:"Roar of Time"},
{ name:"Spacial Rend"},
{ name:"Lunar Dance"},
{ name:"Crush Grip"},
{ name:"Magma Storm"},
{ name:"Dark Void"},
{ name:"Seed Flare"},
{ name:"Ominous Wind"},
{ name:"Shadow Force"},
{ name:"Hone Claws"},
{ name:"Wide Guard"},
{ name:"Guard Split"},
{ name:"Power Split"},
{ name:"Wonder Room"},
{ name:"Psyshock"},
{ name:"Venoshock"},
{ name:"Autotomize"},
{ name:"Rage Powder"},
{ name:"Telekinesis"},
{ name:"Magic Room"},
{ name:"Smack Down"},
{ name:"Storm Throw"},
{ name:"Flame Burst"},
{ name:"Sludge Wave"},
{ name:"Quiver Dance"},
{ name:"Heavy Slam"},
{ name:"Synchronoise"},
{ name:"Electro Ball"},
{ name:"Soak"},
{ name:"Flame Charge"},
{ name:"Coil"},
{ name:"Low Sweep"},
{ name:"Acid Spray"},
{ name:"Foul Play"},
{ name:"Simple Beam"},
{ name:"Entrainment"},
{ name:"After You"},
{ name:"Round"},
{ name:"Echoed Voice"},
{ name:"Chip Away"},
{ name:"Clear Smog"},
{ name:"Stored Power"},
{ name:"Quick Guard"},
{ name:"Ally Switch"},
{ name:"Scald"},
{ name:"Shell Smash"},
{ name:"Heal Pulse"},
{ name:"Hex"},
{ name:"Sky Drop"},
{ name:"Shift Gear"},
{ name:"Circle Throw"},
{ name:"Incinerate"},
{ name:"Quash"},
{ name:"Acrobatics"},
{ name:"Reflect Type"},
{ name:"Retaliate"},
{ name:"Final Gambit"},
{ name:"Bestow"},
{ name:"Inferno"},
{ name:"Water Pledge"},
{ name:"Fire Pledge"},
{ name:"Grass Pledge"},
{ name:"Volt Switch"},
{ name:"Struggle Bug"},
{ name:"Bulldoze"},
{ name:"Frost Breath"},
{ name:"Dragon Tail"},
{ name:"Work Up"},
{ name:"Electroweb"},
{ name:"Wild Charge"},
{ name:"Drill Run"},
{ name:"Dual Chop"},
{ name:"Heart Stamp"},
{ name:"Horn Leech"},
{ name:"Sacred Sword"},
{ name:"Razor Shell"},
{ name:"Heat Crash"},
{ name:"Leaf Tornado"},
{ name:"Steamroller"},
{ name:"Cotton Guard"},
{ name:"Night Daze"},
{ name:"Psystrike"},
{ name:"Tail Slap"},
{ name:"Hurricane"},
{ name:"Head Charge"},
{ name:"Gear Grind"},
{ name:"Searing Shot"},
{ name:"Techno Blast"},
{ name:"Relic Song"},
{ name:"Secret Sword"},
{ name:"Glaciate"},
{ name:"Bolt Strike"},
{ name:"Blue Flare"},
{ name:"Fiery Dance"},
{ name:"Freeze Shock"},
{ name:"Ice Burn"},
{ name:"Snarl"},
{ name:"Icicle Crash"},
{ name:"V-create"},
{ name:"Fusion Flare"},
{ name:"Fusion Bolt"},
{ name:"Flying Press"},
{ name:"Mat Block"},
{ name:"Belch"},
{ name:"Rototiller"},
{ name:"Sticky Web"},
{ name:"Fell Stinger"},
{ name:"Phantom Force"},
{ name:"Trick-or-Treat"},
{ name:"Noble Roar"},
{ name:"Ion Deluge"},
{ name:"Parabolic Charge"},
{ name:"Forest's Curse"},
{ name:"Petal Blizzard"},
{ name:"Freeze-Dry"},
{ name:"Disarming Voice"},
{ name:"Parting Shot"},
{ name:"Topsy-Turvy"},
{ name:"Draining Kiss"},
{ name:"Crafty Shield"},
{ name:"Flower Shield"},
{ name:"Grassy Terrain"},
{ name:"Misty Terrain"},
{ name:"Electrify"},
{ name:"Play Rough"},
{ name:"Fairy Wind"},
{ name:"Moonblast"},
{ name:"Boomburst"},
{ name:"Fairy Lock"},
{ name:"King's Shield"},
{ name:"Play Nice"},
{ name:"Confide"},
{ name:"Diamond Storm"},
{ name:"Steam Eruption"},
{ name:"Hyperspace Hole"},
{ name:"Water Shuriken"},
{ name:"Mystical Fire"},
{ name:"Spiky Shield"},
{ name:"Aromatic Mist"},
{ name:"Eerie Impulse"},
{ name:"Venom Drench"},
{ name:"Powder"},
{ name:"Geomancy"},
{ name:"Magnetic Flux"},
{ name:"Happy Hour"},
{ name:"Electric Terrain"},
{ name:"Dazzling Gleam"},
{ name:"Celebrate"},
{ name:"Hold Hands"},
{ name:"Baby-Doll Eyes"},
{ name:"Nuzzle"},
{ name:"Hold Back"},
{ name:"Infestation"},
{ name:"Power-Up Punch"},
{ name:"Oblivion Wing"},
{ name:"Thousand Arrows"},
{ name:"Thousand Waves"},
{ name:"Land's Wrath"},
{ name:"Light of Ruin"},
{ name:"Origin Pulse"},
{ name:"Precipice Blades"},
{ name:"Dragon Ascent"},
{ name:"Hyperspace Fury"},
{ name:"Breakneck Blitz"},
{ name:"Breakneck Blitz"},
{ name:"All-Out Pummeling"},
{ name:"All-Out Pummeling"},
{ name:"Supersonic Skystrike"},
{ name:"Supersonic Skystrike"},
{ name:"Acid Downpour"},
{ name:"Acid Downpour"},
{ name:"Tectonic Rage"},
{ name:"Tectonic Rage"},
{ name:"Continental Crush"},
{ name:"Continental Crush"},
{ name:"Savage Spin-Out"},
{ name:"Savage Spin-Out"},
{ name:"Never-Ending Nightmare"},
{ name:"Never-Ending Nightmare"},
{ name:"Corkscrew Crash"},
{ name:"Corkscrew Crash"},
{ name:"Inferno Overdrive"},
{ name:"Inferno Overdrive"},
{ name:"Hydro Vortex"},
{ name:"Hydro Vortex"},
{ name:"Bloom Doom"},
{ name:"Bloom Doom"},
{ name:"Gigavolt Havoc"},
{ name:"Gigavolt Havoc"},
{ name:"Shattered Psyche"},
{ name:"Shattered Psyche"},
{ name:"Subzero Slammer"},
{ name:"Subzero Slammer"},
{ name:"Devastating Drake"},
{ name:"Devastating Drake"},
{ name:"Black Hole Eclipse"},
{ name:"Black Hole Eclipse"},
{ name:"Twinkle Tackle"},
{ name:"Twinkle Tackle"},
{ name:"Catastropika"},
{ name:"Shore Up"},
{ name:"First Impression"},
{ name:"Baneful Bunker"},
{ name:"Spirit Shackle"},
{ name:"Darkest Lariat"},
{ name:"Sparkling Aria"},
{ name:"Ice Hammer"},
{ name:"Floral Healing"},
{ name:"High Horsepower"},
{ name:"Strength Sap"},
{ name:"Solar Blade"},
{ name:"Leafage"},
{ name:"Spotlight"},
{ name:"Toxic Thread"},
{ name:"Laser Focus"},
{ name:"Gear Up"},
{ name:"Throat Chop"},
{ name:"Pollen Puff"},
{ name:"Anchor Shot"},
{ name:"Psychic Terrain"},
{ name:"Lunge"},
{ name:"Fire Lash"},
{ name:"Power Trip"},
{ name:"Burn Up"},
{ name:"Speed Swap"},
{ name:"Smart Strike"},
{ name:"Purify"},
{ name:"Revelation Dance"},
{ name:"Core Enforcer"},
{ name:"Trop Kick"},
{ name:"Instruct"},
{ name:"Beak Blast"},
{ name:"Clanging Scales"},
{ name:"Dragon Hammer"},
{ name:"Brutal Swing"},
{ name:"Aurora Veil"},
{ name:"Sinister Arrow Raid"},
{ name:"Malicious Moonsault"},
{ name:"Oceanic Operetta"},
{ name:"Guardian of Alola"},
{ name:"Soul-Stealing 7-Star Strike"},
{ name:"Stoked Sparksurfer"},
{ name:"Pulverizing Pancake"},
{ name:"Extreme Evoboost"},
{ name:"Genesis Supernova"},
{ name:"Shell Trap"},
{ name:"Fleur Cannon"},
{ name:"Psychic Fangs"},
{ name:"Stomping Tantrum"},
{ name:"Shadow Bone"},
{ name:"Accelerock"},
{ name:"Liquidation"},
{ name:"Prismatic Laser"},
{ name:"Spectral Thief"},
{ name:"Sunsteel Strike"},
{ name:"Moongeist Beam"},
{ name:"Tearful Look"},
{ name:"Zing Zap"},
{ name:"Nature's Madness"},
{ name:"Multi-Attack"},
{ name:"10,000,000 Volt Thunderbolt"},
{ name:"Mind Blown"},
{ name:"Plasma Fists"},
{ name:"Photon Geyser"},
{ name:"Light That Burns the Sky"},
{ name:"Searing Sunraze Smash"},
{ name:"Menacing Moonraze Maelstrom"},
{ name:"Let's Snuggle Forever"},
{ name:"Splintered Stormshards"},
{ name:"Clangorous Soulblaze"}]

export default moveNames;
